### ISSUE TITLE
email regexp

### ISSUE THREAD

**Issue by mathroc** [TYVRNET/SRL#12]
the first exemple of this lib is a very basic email matching regexp. I would suggest to replace this with something else. Using regexp for matching email addresses is often a [bad idea](https://davidcel.is/posts/stop-validating-email-addresses-with-regex/) and this example suggests it's fine and/or that this regexp is actually correct for validating email

https://fightingforalostcause.net/content/misc/2006/compare-email-regex.php

**Comment by KarimGeiger** [comment]
I agree with you on validating emails using regular expressions is a bad idea, but the example spans further and parses emails out of plain text. I've updated the website and added a paragraph to inform about this, in the first step.

Maybe we'll find a better example to show off on the page.

**Comment by mathroc** [comment]
thx for adding that comment on the website @KarimGeiger 
I'll come back if I think of an useful example to show off
