### ISSUE TITLE
"Either" really means "Any"

### ISSUE THREAD

**Issue by thinkhuman** [TYVRNET/SRL#16]
In English, "either" means a choice between two ("Choose either A or B). For three or more, the word is "any" (Choose any of these: A, B, C, or D). The "either" keyword is jarring and confusing.

How about changing "Either" to "Any", because that seems to be the syntax--"any of the following".

**Comment by KarimGeiger** [comment]
Yes, this is planned as it makes definitely more sense. It was discussed in #8 but having an extra issue for that isn't too bad.

**Comment by thinkhuman** [comment]
@KarimGeiger Ah sorry, didn't see #8.
