### ISSUE TITLE
Problems with usage of `uppercase letter`

### ISSUE THREAD

**Issue by mandarg** [TYVRNET/SRL#17]
The query 

```
begin with (digit once),
any of (letter, digit, uppercase letter) once or more,
must end
```

fails to compile, with the error

> The SRL Query contains an error: Invalid parameter given for `digit`.

But the same query, if rewritten as

```
begin with (digit once),
any of (uppercase letter, letter, digit) once or more,
must end
```

...seems to compile correctly, and matches my test string `1ABCdef`. From the error message, I guess uppercase is being passed as a parameter to `digit` in the first example?

**Comment by KarimGeiger** [comment]
Thank you for reporting!
