### ISSUE TITLE
Exact range quantifier missing

### ISSUE THREAD

**Issue by Baldrs** [TYVRNET/SRL#21]
How to implement something like `{2,5}` in SRL? If it is not possible at all, please add it.

**Comment by KarimGeiger** [comment]
It is implemented as [`between x and y times`](https://simple-regex.com/build/57c6a44a407f8) but not documented. I forgot about that.

Thanks for reporting! Will add it to the documentation shortly.

**Comment by KarimGeiger** [comment]
Documentation adjusted: https://simple-regex.com/documentation/quantifiers

**Comment by Baldrs** [comment]
Thanks!
