### ISSUE TITLE
Language File

### ISSUE THREAD

**Issue by CeRBeR666** [TYVRNET/SRL#24]
Hi Karim,
I think you should translation files on your project. I want your query translate to turkish.

**Comment by KarimGeiger** [comment]
Hi,

thanks for the suggestion, but I don't think that's a good idea. Yes, SRL is human readable, but with other languages comes other grammar and syntax. In the end, this will probably be a unmaintainable monster.

**Comment by CeRBeR666** [comment]
Ok, but keep in mind ^^
Amazing work Thank you

**Comment by hoshsadiq** [comment]
Agree with Karim. You don't see any programming language that has syntax in multiple natural languages. It doesn't make a lot of sense!
