### ISSUE TITLE
Why does 'literally' create a noncapturing group?

### ISSUE THREAD

**Issue by nsgonultas** [TYVRNET/SRL#28]
I'm working on a python implementation of srl and I'm wondering why `literally` creates a noncapturing group i.e. `(?: ...)`

**Comment by KarimGeiger** [comment]
Hi @nsgonultas,

it does that to ensure that all quantifiers address the complete word, not only the last character.

By the way, if you like, I can add you to our Slack team and the [official Python repository](https://github.com/SimpleRegex/SRL-Python). That way you can communicate with the other developers.

**Comment by nsgonultas** [comment]
My implementation has little syntax differences and a non-profit license. So I prefer working seperately. However I'm watching this repo and official Python repo. I would like to help if needed :+1:

**Comment by KarimGeiger** [comment]
Alright, have fun then. Let me know when you're done :)
