### ISSUE TITLE
Webapp to test SRLs versus inputs

### ISSUE THREAD

**Issue by francislavoie** [TYVRNET/SRL#7]
Something like this: http://www.phpliveregex.com/ but for SRL would be very useful to test on the fly.

Also a suggested feature would be to generate links that include the SRL base64 encoded in the URL so they can be thrown in comments in the code if we just used the generated regex, to refer back to the SRL and edit it.

This idea came to me when I read this bit in the README

> But if you like, you can build the expression somewhere else and just use the result in your app. If you do that, please keep the code for that query somewhere and link to it, otherwise the Regular Expression will be unreadable just as before.

**Comment by kkirby** [comment]
This: https://simple-regex.com/build?

**Comment by francislavoie** [comment]
Oh I'm blind, I missed that page. Sorry

**Comment by francislavoie** [comment]
That link should probably be throw in the README somewhere

**Comment by KarimGeiger** [comment]
Good point. Will do.
